<?php require('header.php');?>
<section class="row-fluid" >
	<article class="row-fluid span10 offset1" >
		<div id="contenu-adherent ">
			<table id="myTable" class="tablesorter">
				<thead>
					<tr>
						<th>Nom</th>
						<th>Prénom</th>
						<th>Équipe</th>
						<th>Points</th>
					</tr>
				</thead>
				<tbody>
					<tr>
						<td>ALLAIN</td>
						<td>Bastien</td>
						<td>D2</td>
						<td>719</td>
					</tr>
					<tr>
						<td>ANQUETIL</td>
						<td>Sylvie</td>
						<td>Loisir</td>
						<td>500</td>
					</tr>
					<tr>
						<td>AUBINAIS</td>
						<td>Didier</td>
						<td>Loisir</td>
						<td>500</td>
					</tr>

					<tr>
						<td>BEZIEAU</td>
						<td>Alban</td>
						<td>D3/Cadet D1</td>
						<td>608</td>
					</tr>
					<tr>
						<td>BERIEAU</td>
						<td>Sylvain</td>
						<td>Loisir</td>
						<td>500</td>
					</tr>
					<tr>
						<td>BOTTAU</td>
						<td>Sébastien</td>
						<td>D3</td>
						<td>526</td>
					</tr>
					<tr>
						<td>BOURDIN</td>
						<td>Karl</td>
						<td>D1</td>
						<td>777</td>
					</tr>
					<tr>
						<td>CAILLIBOTTE</td>
						<td>Régina</td>
						<td>D5</td>
						<td>500</td>
					</tr>
					<tr>
						<td>CAZAUBON</td>
						<td>Denis</td>
						<td>D3</td>
						<td>687</td>
					</tr>
					<tr>
						<td>CHAMOUILLET</td>
						<td>Yann</td>
						<td>D3</td>
						<td>884</td>
					</tr>
					<tr>
						<td>CHAMOUILLET</td>
						<td>Xavier</td>
						<td>Loisir</td>
						<td>500</td>
					</tr>
					<tr>
						<td>CHARPENTIER</td>
						<td>Mathew</td>
						<td>D5/Cadet D3</td>
						<td>495</td>
					</tr>
					<tr>
						<td>CHIFFOLEAU</td>
						<td>Tom</td>
						<td>Loisir</td>
						<td>500</td>
					</tr>
					<tr>
						<td>CLARET TOURNIER</td>
						<td>Lois</td>
						<td>D2</td>
						<td>1070</td>
					</tr>
					<tr>
						<td>CORSINI</td>
						<td>Emmanuel</td>
						<td>D2</td>
						<td>815</td>
					</tr>
					<tr>
						<td>COUSIN</td>
						<td>Kévin</td>
						<td>Loisir</td>
						<td>500</td>
					</tr>
					<tr>
						<td>CUZOU</td>
						<td>Nicolas</td>
						<td>Loisir</td>
						<td>500</td>
					</tr>
					<tr>
						<td>DUPONT</td>
						<td>Lilian</td>
						<td>D5/Junior D1</td>
						<td>567</td>
					</tr>
					<tr>
						<td>EVEILLARD</td>
						<td>Anne</td>
						<td>Loisir</td>
						<td>500</td>
					</tr>

					<tr>
						<td>GIRAULT</td>
						<td>Quentin</td>
						<td>Junior D1/D1</td>
						<td>763</td>
					</tr>
					<tr>
						<td>GUERIN</td>
						<td>Yoann</td>
						<td>D3</td>
						<td>919</td>
					</tr>
					<tr>
						<td>HERBRETEAU</td>
						<td>Kévin</td>
						<td>Loisir</td>
						<td>500</td>
					</tr>
					<tr>
						<td>JARDIN</td>
						<td>Pierre André</td>
						<td>D5</td>
						<td>500</td>
					</tr>
					<tr>
						<td>KOPLEWICZ</td>
						<td>Antony</td>
						<td>Loisir</td>
						<td>500</td>
					</tr>
					<tr>
						<td>LE BIHAN</td>
						<td>Lucas</td>
						<td>Loisir</td>
						<td>500</td>
					</tr>
					<tr>
						<td>LE BOTH</td>
						<td>Teddy</td>
						<td>D2/Junior D1</td>
						<td>972</td>
					</tr>
					<tr>
						<td>LE BRAS</td>
						<td>Fabien</td>
						<td>Cadet D3</td>
						<td>489</td>
					</tr>
					<tr>
						<td>LE BRAS</td>
						<td>Nicole</td>
						<td>Loisir</td>
						<td>500</td>
					</tr>
					<tr>
						<td>LEBOURSICAUD</td>
						<td>Ryan</td>
						<td>D3</td>
						<td>982</td>
					</tr>
					<tr>
						<td>LEBOURSICAUD</td>
						<td>Kylian</td>
						<td>D5</td>
						<td>500</td>
					</tr>
					<tr>
						<td>LECARER</td>
						<td>Kévin</td>
						<td>Loisir</td>
						<td>500</td>
					</tr>
					<tr>
						<td>LEFORT</td>
						<td>Alex</td>
						<td>Loisir</td>
						<td>503</td>
					</tr>
					<tr>
						<td>LEFORT</td>
						<td>Théo</td>
						<td>Cadet D1</td>
						<td>721</td>
					</tr>
					<tr>
						<td>LEFRERE</td>
						<td>Gaetan</td>
						<td>D2</td>
						<td>996</td>
					</tr>
					<tr>
						<td>LEMASLE</td>
						<td>Léo</td>
						<td>Loisir</td>
						<td>500</td>
					</tr>
					<tr>
						<td>LEMASLE</td>
						<td>Catherine</td>
						<td>Loisir</td>
						<td>500</td>
					</tr>
					<tr>
						<td>LICOIS</td>
						<td>Anthony</td>
						<td>D1</td>
						<td>1491</td>
					</tr>
					<tr>
						<td>LOUHICHI</td>
						<td>Rayenne</td>
						<td>Loisir</td>
						<td>500</td>
					</tr>
					<tr>
						<td>MANDART</td>
						<td>Emmanuel</td>
						<td>D5</td>
						<td>500</td>
					</tr>
					<tr>
						<td>MANDART</td>
						<td>Emmanuel</td>
						<td>Loisir</td>
						<td>500</td>
					</tr>
					<tr>
						<td>MARCHAND</td>
						<td>Florian</td>
						<td>Loisir</td>
						<td>500</td>
					</tr>
					<tr>
						<td>MENARD</td>
						<td>Catherine</td>
						<td>Loisir</td>
						<td>500</td>
					</tr>
					<tr>
						<td>MENARD</td>
						<td>Dominique</td>
						<td>Loisir</td>
						<td>500</td>
					</tr>
					<tr>
						<td>NAVINEL DUBOIS</td>
						<td>Mathis</td>
						<td>Loisir</td>
						<td>500</td>
					</tr>
					<tr>
						<td>N GUYEN</td>
						<td>Thomas</td>
						<td>Loisir</td>
						<td>565</td>
					</tr>
					<tr>
						<td>Pascual</td>
						<td>Florent</td>
						<td>D5</td>
						<td>520</td>
					</tr>
					<tr>
						<td>Pelletier</td>
						<td>Benjamin</td>
						<td>D3</td>
						<td>554</td>
					</tr>
					<tr>
						<td>PIERRE</td>
						<td>Aurélie</td>
						<td>D1</td>
						<td>1083</td>
					</tr>
					<tr>
						<td>PIERRE</td>
						<td>Eric</td>
						<td>D2</td>
						<td>1204</td>
					</tr>
					<tr>
						<td>PIERRE</td>
						<td>Philippe</td>
						<td>D3</td>
						<td>1090</td>
					</tr>
					<tr>
						<td>PINEAU</td>
						<td>Camille</td>
						<td>Cadet D1/D4</td>
						<td>784</td>
					</tr>
					<tr>
						<td>PINEAU</td>
						<td>Mathieu</td>
						<td>Junior D1/D4</td>
						<td>711</td>
					</tr>
					<tr>
						<td>PINEAU</td>
						<td>Nathalie</td>
						<td>Loisir</td>
						<td>500</td>
					</tr>
					<tr>
						<td>PINEAU</td>
						<td>Philippe</td>
						<td>D4</td>
						<td>599</td>
					</tr>
					<tr>
						<td>RICHOMME</td>
						<td>Jérémy</td>
						<td>Loisir</td>
						<td>500</td>
					</tr>
					<tr>
						<td>RICHOMME</td>
						<td>Thomas</td>
						<td>Cadet D3</td>
						<td>492</td>
					</tr>
					<tr>
						<td>RICOUL</td>
						<td>Tanguy</td>
						<td>D1</td>
						<td>1070</td>
					</tr>
					<tr>
						<td>SEBILO</td>
						<td>Gregory</td>
						<td>D1</td>
						<td>1630</td>
					</tr>
					<tr>
						<td>TEXIER</td>
						<td>Marie</td>
						<td>Loisir</td>
						<td>500</td>
					</tr>
					<tr>
						<td>VAILLAND</td>
						<td>Patrice</td>
						<td>D1</td>
						<td>1299</td>
					</tr>
					<tr>
						<td>VERON</td>
						<td>Jean</td>
						<td>Cadet D3</td>
						<td>498</td>
					</tr>
				</tbody>
			</table>

		</div>
	</article>
</section>
<?php require('footer.php');?>	